s = set()
n= input("Enter value: ")
s.add(int(n))
n= input("Enter value: ")
s.add(int(n))
n= input("Enter value: ")
s.add(int(n))
n= input("Enter value: ")
s.add(int(n))
n= input("Enter value: ")
s.add(int(n))
n= input("Enter value: ")
s.add(int(n))
n= input("Enter value: ")
s.add(int(n))
n= input("Enter value: ")
s.add(int(n))

print(s)